# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests

on: [pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
              env:
                  SECRET_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SECRET_SUPABASE_SERVICE_ROLE_KEY }}
                  SECRET_SUPABASE_URL: ${{ secrets.SECRET_SUPABASE_URL }}
                  SECRET_DMOJ_API_TOKEN: ${{ secrets.SECRET_DMOJ_API_TOKEN }}
            - run: npm install
            - run: npx playwright install
            - run: npm test
